version: 2

sources:
  - name: adventureworks
    database: raw_dbt
    schema: adventureworks
    tables:
      - name: adventureworks_calendar_lookup
      - name: adventureworks_customer_lookup
      - name: adventureworks_product_categories_lookup
      - name: adventureworks_product_lookup
      - name: adventureworks_product_subcategories_lookup
      - name: adventureworks_returns_data
      - name: adventureworks_sales_data_2020
      - name: adventureworks_sales_data_2021
      - name: adventureworks_sales_data_2022
      - name: adventureworks_territory_lookup